name: 马小齐的博客
url: goodluckforme.github.io
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: rouge
paginate: 20
  

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
